#!/Users/ajb/dev/bin/perl -T

use warnings;
use strict;
use lib qw(lib);

use message_queue::controller;
use message_queue::util;

use message_queue::model::message;
use message_queue::model::queue;

use message_queue::view::error;
use message_queue::view::message;
use message_queue::view::queue;

our $VERSION = do { my ($r) = q$LastChangedRevision: 300 $ =~ /(\d+)/smx; $r; };

main();
0;

sub main {
  my $util = message_queue::util->new();
  message_queue::controller->handler($util);
}
 
